### ISSUE TITLE
There are many FT error in build

### ISSUE THREAD

**Issue by Yamilemon** [ningshanwutuobang/Kirikiroid2#3]
cmake version：3.6.4111459
android：Android Studio Arctic Fox | 2020.3.1 Patch 3
Build #AI-203.7717.56.2031.7784292, built on October 1, 2021
Runtime version: 11.0.10+0-b96-7249189 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Windows 7 6.1
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 12

![20220209112155](https://user-images.githubusercontent.com/22819281/153116041-bcc856e2-ff71-4a3d-a75f-86bbc379ca2f.png)

![image](https://user-images.githubusercontent.com/22819281/153116751-4538ee90-b8bf-4094-8798-b0d2b091d0c9.png)

Is there any problem in the source file of cocos2d?

**Comment by ningshanwutuobang** [comment]
I have found the reason,  `src/core/visual/FreeType.h` conflict with `freetype.h` in Windows. I will rename it to fix it.

**Comment by Yamilemon** [comment]
> I have found the reason, `src/core/visual/FreeType.h` conflict with `freetype.h` in Windows. I will rename it to fix it.

OK, I also found this problem. I have successfully built it. Thank you very much
