### ISSUE TITLE
A question about std::bad_alloc

### ISSUE THREAD

**Issue by Yamilemon** [ningshanwutuobang/Kirikiroid2#4]
When I run the game, sometimes there are std::bad_alloc errors.
![OD$PSRGF9WAEIFDOPYHGGBW](https://user-images.githubusercontent.com/22819281/156739131-0a5f6986-d6df-40b3-aa0f-f0ab6448fadd.jpg)
I know this is written in readme, but I want to know how it happened and how to avoid it. This error doesn't happen every time I run the game. In most cases, my game can run smoothly, So I can't find the reason for this error.

**Comment by ningshanwutuobang** [comment]
I think it's because the file [aligned_allocator.h](https://github.com/ningshanwutuobang/Kirikiroid2/blob/new/src/core/visual/gl/aligned_allocator.h) is missing. I couldn't find a better implementation.

**Comment by ningshanwutuobang** [comment]
Another possible reason is the string heap in 

https://github.com/ningshanwutuobang/Kirikiroid2/commit/b377a0efe8c2ddce564eec5f9ae8c8d58bea29e2#diff-d2d5d0f3872f71c9a933b52445ad5d55ead0979473bc813a1cff379f2f660a54

**Comment by BBplux** [comment]
老哥你是怎么编译跑到这步的，为什么我游戏都进不去
![image](https://user-images.githubusercontent.com/44959801/190421791-43c7e97a-82d0-4cf0-ab0d-eb6f6b3aed3e.png)

**Comment by Yamilemon** [comment]
> 老哥你是怎么编译跑到这步的，为什么我游戏都进不去 ![image](https://user-images.githubusercontent.com/44959801/190421791-43c7e97a-82d0-4cf0-ab0d-eb6f6b3aed3e.png)

你把xp3解包以后把这个函数补上（补个空函数）再封回去不就有了，反正看哪里报错就哪里做兼容，自己看着来吧。

**Comment by BBplux** [comment]
> > 老哥你是怎么编译跑到这步的，为什么我游戏都进不去 ![image](https://user-images.githubusercontent.com/44959801/190421791-43c7e97a-82d0-4cf0-ab0d-eb6f6b3aed3e.png)
> 
> 你把xp3解包以后把这个函数补上（补个空函数）再封回去不就有了，反正看哪里报错就哪里做兼容，自己看着来吧。

能参考一下吗

**Comment by ryank231231** [comment]
> > > 老哥你是怎么编译跑到这步的，为什么我游戏都进不去 ![image](https://user-images.githubusercontent.com/44959801/190421791-43c7e97a-82d0-4cf0-ab0d-eb6f6b3aed3e.png)
> > 
> > 
> > 你把xp3解包以后把这个函数补上（补个空函数）再封回去不就有了，反正看哪里报错就哪里做兼容，自己看着来吧。
> 
> 能参考一下吗

参考下zeas2的补丁库里面的就行（

**Comment by ryank231231** [comment]
> 老哥你是怎么编译跑到这步的，为什么我游戏都进不去 ![image](https://user-images.githubusercontent.com/44959801/190421791-43c7e97a-82d0-4cf0-ab0d-eb6f6b3aed3e.png)

`Window.registerExEvent = function(){};`

**Comment by BBplux** [comment]
大佬，编译时  ld: error: duplicate symbol: 这个问题您是怎么解决的

**Comment by BBplux** [comment]
@ryank231231 @Yamilemon 大佬编译时  ld: error: duplicate symbol: 这个报错是怎么解决的
